// const types = {
//     ADD_APPOINTMENT: "ADD_APPOINTMENT", 
//     REMOVE_APPOINTMENT: "REMOVE_APPOINTMENT"
// }

// export default types

export const ADD_APPOINTMENT = "ADD_APPOINTMENT"
export const REMOVE_APPOINTMENT = "REMOVE_APPOINTMENT"
export const GET_BOOKED = "GET_BOOKED"
export const UPDATE_BOOKED = "UPDATE_BOOKED"

export const GET_DOCTORS = "GET_DOCTORS"

export const SIGNIN_USER = "SIGNIN_USER"
export const SIGNOUT_USER = "SIGNOUT_USER"

export const NEW_ERROR = "NEW_ERROR"
export const REMOVE_ERROR = "REMOVE_ERROR"

export const GET_DOCTOR_URLS = "GET_DOCTOR_URLS"
export const ADMIN_GET_DOCTORS = "ADMIN_GET_DOCTORS"

